services:

  dogenet-web-client:
    container_name: dogenet-web-client
    build:
      context: ./DogeNetWebClient
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    ports:
      - 4200:4200

  dogenet-identity:
    container_name: dogenet-identity
    build:
      context: ./DogeNet.IdentityServer
      dockerfile: Dockerfile
    working_dir: /identity
    ports:
      - 10001:10001

  dogenet-web-api:
    container_name: dogenet-web-api
    build:
      context: ./DogeNet.WebApi
      dockerfile: Dockerfile
    working_dir: /api
    ports:
      - 7001:7001

