version: '3.4'

services:
  dogenet.webapi:
    image: ${DOCKER_REGISTRY-}dogenetwebapi
    build:
      context: .
      dockerfile: DogeNet.WebApi/Dockerfile          
    links:
      - dogenet.identityserver
    depends_on:
    - sql-server-db

  dogenet.identityserver:
    image: ${DOCKER_REGISTRY-}dogenetidentityserver
    build:
      context: .
      dockerfile: DogeNet.IdentityServer/Dockerfile
    depends_on:
      - sql-server-db

  dogenet-web-client:
    container_name: dogenet-web-client
    build:
      context: ./DogeNetWebClient
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    ports:
      - 4200:4200
      
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "!dogenet2022#"


