import { Component, OnInit } from '@angular/core';
import { FriendsDetailsModel } from 'src/app/core/api/models';

@Component({
  selector: 'app-friends-grid',
  templateUrl: './friends-grid.component.html',
  styleUrls: ['./friends-grid.component.css'],
})
export class FriendsGridComponent {
  public items: FriendsDetailsModel[] = [
    {
      id: 0,
      userName: 'shiba',
      firstName: 'Inu',
      lastName: 'Shiba',
      createdAt: '2022-06-30T12:14:53.562Z',
      statusId: 0,
      title: 'test_title',
      avatarImg: 'https://material.angular.io/assets/img/examples/shiba2.jpg',
      coverImg: 'string',
      cityId: 0,
      bio: 'test_bio',
    },
    {
      id: 0,
      userName: 'shiba',
      firstName: 'Inu',
      lastName: 'Shiba',
      createdAt: '2022-06-30T12:14:53.562Z',
      statusId: 0,
      title: 'test_title',
      avatarImg: 'https://material.angular.io/assets/img/examples/shiba2.jpg',
      coverImg: 'string',
      cityId: 0,
      bio: 'test_bio',
    },
    {
      id: 0,
      userName: 'shiba',
      firstName: 'Inu',
      lastName: 'Shiba',
      createdAt: '2022-06-30T12:14:53.562Z',
      statusId: 0,
      title: 'test_title',
      avatarImg: 'https://material.angular.io/assets/img/examples/shiba2.jpg',
      coverImg: 'string',
      cityId: 0,
      bio: 'test_bio',
    },
    {
      id: 0,
      userName: 'shiba',
      firstName: 'Inu',
      lastName: 'Shiba',
      createdAt: '2022-06-30T12:14:53.562Z',
      statusId: 0,
      title: 'test_title',
      avatarImg: 'https://material.angular.io/assets/img/examples/shiba2.jpg',
      coverImg: 'string',
      cityId: 0,
      bio: 'test_bio',
    },
    {
      id: 0,
      userName: 'shiba',
      firstName: 'Inu',
      lastName: 'Shiba',
      createdAt: '2022-06-30T12:14:53.562Z',
      statusId: 0,
      title: 'test_title',
      avatarImg: 'https://material.angular.io/assets/img/examples/shiba2.jpg',
      coverImg: 'string',
      cityId: 0,
      bio: 'test_bio',
    },
    {
      id: 0,
      userName: 'shiba',
      firstName: 'Inu',
      lastName: 'Shiba',
      createdAt: '2022-06-30T12:14:53.562Z',
      statusId: 0,
      title: 'test_title',
      avatarImg: 'https://material.angular.io/assets/img/examples/shiba2.jpg',
      coverImg: 'string',
      cityId: 0,
      bio: 'test_bio',
    },
    {
      id: 0,
      userName: 'shiba',
      firstName: 'Inu',
      lastName: 'Shiba',
      createdAt: '2022-06-30T12:14:53.562Z',
      statusId: 0,
      title: 'test_title',
      avatarImg: 'https://material.angular.io/assets/img/examples/shiba2.jpg',
      coverImg: 'string',
      cityId: 0,
      bio: 'test_bio',
    },
    {
      id: 0,
      userName: 'shiba',
      firstName: 'Inu',
      lastName: 'Shiba',
      createdAt: '2022-06-30T12:14:53.562Z',
      statusId: 0,
      title: 'test_title',
      avatarImg: 'https://material.angular.io/assets/img/examples/shiba2.jpg',
      coverImg: 'string',
      cityId: 0,
      bio: 'test_bio',
    },
  ];
}
